frontend/.gitignore
CSS 파일은 무시: assets/ 폴더 내의 모든 파일 깃 ignore.
CSS, font, scss 파일들은 깃헙에 업로드 하지마세요
=> [feat] gitignore 파일 업데이트

techUpFrontend/components/header/component/top-categories.vue, techUpFrontend/components/header/header-one.vue, techUpFrontend/components/modal/modal-product.vue, techUpFrontend/components/modal/modal-video.vue, techUpFrontend/components/product-details/product-details-countdown.vue, techUpFrontend/components/product-details/product-details-thumb.vue, techUpFrontend/components/product-details/product-details-wrapper.vue
=> 메인 페이지 에러 수정 및 모바일 헤더 주석처리

techUpFrontend/components/forms/update-profile-form.vue, techUpFrontend/components/profile/profile-address.vue, techUpFrontend/components/profile/profile-info.vue, techUpFrontend/components/profile/profile-main.vue, techUpFrontend/components/profile/profile-nav.vue, techUpFrontend/components/profile/profile-notification.vue, techUpFrontend/components/profile/profile-orders.vue, techUpFrontend/components/profile/profile-password.vue
=> [Fix] add korean translation to profile

techUpFrontend/components/breadcrumb/breadcrumb-4.vue, techUpFrontend/components/wishlist/wishlist-area.vue, techUpFrontend/components/wishlist/wishlist-item.vue, techUpFrontend/pages/404.vue, techUpFrontend/pages/wishlist.vue
=> [Feat] add wishlist page

techUpFrontend/components/coupon/coupon-area.vue, techUpFrontend/components/coupon/coupon-item.client.vue, techUpFrontend/package-lock.json, techUpFrontend/package.json, techUpFrontend/pages/coupons.vue
=> [Feat] add coupon page

techUpFrontend/components/forgot/forgot-area.vue, techUpFrontend/components/forms/register-form.vue, techUpFrontend/pages/forgot.vue
* 닉네임 중복 방지 버튼
* 이메일 인증 버튼 및 버튼을 눌렀을 때 나타나는 타이머와 인증번호란 추가
* 비밀번호 찾기 페이지 추가
=> [Feat] 중복 방지 버튼 및 비밀번호 찾기 페이지 추가 

techUpFrontend/components/header/component/top-menu.vue, techUpFrontend/components/header/header-one.vue, techUpFrontend/components/header/header-two.vue
설정 드롭다운 메뉴 한글화
검색창이 특정 너비 범위에서 로고를 가리는 문제 수정
=> [Fix] 헤더 추가 수정

techUpFrontend/layouts/components/DefaultLayoutWithVerticalNav.vue, techUpFrontend/layouts/components/Footer.vue, techUpFrontend/layouts/components/NavItems.vue, techUpFrontend/layouts/components/NavbarThemeSwitcher.vue, techUpFrontend/layouts/components/UserProfile.vue
build는 되지만 deprecated된 오류 몇개 남아있음.
=> 빌드 안되는 오류 수정

techUpFrontend/components/header/header-four.vue, techUpFrontend/components/header/header-three.vue, techUpFrontend/components/header/header-two.vue, techUpFrontend/nuxt.config.js, techUpFrontend/package-lock.json, techUpFrontend/package.json, techUpFrontend/pages/shop.vue, techUpFrontend/plugins/axios.js
=> BTS-89 제품 기능 - feat - 백엔드와 프론트엔드 연결을 위한 프록시 추가

techUpFrontend/components/breadcrumb/breadcrumb-1.vue
=> [fix] 제품 목록 페이지 경고 메세지 해결

techUpFrontend/components/shop/shop-area.vue, techUpFrontend/pages/shop.vue, techUpFrontend/pinia/useProductBackStore.js, techUpFrontend/pinia/useProductFilterBackStore.js
BTS-54, 122 [feat] JSON 형태로 로컬에 저장된 데이터 대신 백엔드로부터 리스트를 받아서 표시하도록 수정
=> [feat] 제품목록 백엔드로부터 가져와서 표시

techUpFrontend/components/admin/admin-coupon-create.vue, techUpFrontend/components/admin/admin-coupons.vue, techUpFrontend/components/coupon/coupon-item.admin.vue
=> [Feat] 쿠폰 등록 및 조회 기초 공사 완료

techUpFrontend/components/product-details/product-details-tab-nav.vue, techUpFrontend/components/product-details/product-details-wrapper.vue, techUpFrontend/components/product/fashion/product-item.vue, techUpFrontend/components/product/item.client.vue, techUpFrontend/pinia/useCartStore.js
BTS-138
상세 페이지 리뷰/설명 탭 추가
수량 상태 표시 안되는 오류 수정
=> 상세 페이지 디테일 추가

techUpFrontend/components/admin/admin-device-item.vue, techUpFrontend/components/wishlist/wishlist-area.vue, techUpFrontend/pages/search.vue, techUpFrontend/pinia/useCartStore.js
BTS-123 상품 검색 페이지 이식
기타 데이터 속성 이름 필드 동일하게 수정
=> 상품 검색 페이지 이식

techUpFrontend/components/header/component/top-menu.vue, techUpFrontend/components/login/login-social.vue, techUpFrontend/components/profile/profile-main.vue, techUpFrontend/pinia/useUserStore.js
- 마이페이지 로그아웃
-  헤더 로그아웃
- 로그인 / 로그아웃에 따른 헤더 변경
- 새로고침시 백엔드 통신을 통해 로그인 여부 확인 로직 추가
=> BTS-41 [Feat] 로그아웃 기능

techUpFrontend/components/product/fashion/product-item.vue, techUpFrontend/components/product/item.client.vue, techUpFrontend/components/product/list-item.vue, techUpFrontend/components/wishlist/wishlist-item.vue, techUpFrontend/pinia/useWishlistStore.js
BTS-125 위시리스트 기능 수정 완료.
기본 기능(조회, 추가, 삭제), 구현 완료
위시리스트 백엔드와 연결
디테일 수정:
위시리스트에 있는 제품은 있다고 표시
위시리스트에 있는 제품 가격이 출력되지 않는 오류 수정
위시리스트에 할인가 출력
위시리스트 로그아웃 된 상태에서 집입 시 로그인 페이지로 연결
위시리스트 서로 다른 계정에서 접속시 다른 위시리스트 연결
위시리스트에 있는 항목 장바구니에 추가
=> 위시리스트 디테일 수정

techUpFrontend/components/cart/cart-area.vue, techUpFrontend/components/cart/cart-item.vue, techUpFrontend/components/compare/compare-area.vue, techUpFrontend/components/header/component/main-right.vue, techUpFrontend/components/header/header-one.vue, techUpFrontend/components/offcanvas/offcanvas-cart-sidebar.vue, techUpFrontend/components/product-details/product-details-wrapper.vue, techUpFrontend/components/product/fashion/product-item.vue, techUpFrontend/components/product/item.client.vue, techUpFrontend/components/product/list-item.vue, techUpFrontend/components/wishlist/wishlist-item.vue, techUpFrontend/pinia/useCartStore.js, techUpFrontend/pinia/useWishlistStore.js
상품 장바구니에 추가, 삭제, 수량 변경 기능 추가
BTS-110, 111, 112, 117
=> [feat] 장바구니 백엔드와 연결

techUpFrontend/components/cart/cart-area.vue, techUpFrontend/components/cart/cart-item.vue, techUpFrontend/components/product/beauty/product-beauty-item.vue, techUpFrontend/components/product/list-item.vue, techUpFrontend/components/shop/sidebar/index.vue, techUpFrontend/components/shop/sidebar/price-filter.vue, techUpFrontend/components/shop/sidebar/shop-sidebar-load-more.vue, techUpFrontend/pinia/useCartStore.js
BTS-111 장바구니에 항목 추가 시 제품의 재고수를 확인하고 부족하다면 경고를 띄우도록 수정
=> 장바구니 기능 디테일 수

techUpFrontend/components/cart/cart-item.vue, techUpFrontend/components/wishlist/wishlist-item.vue, techUpFrontend/pinia/useCartStore.js
=> 장바구니 비우기 기능 추가

techUpFrontend/components/cart/cart-item.vue, techUpFrontend/components/shop/sidebar/reset-filter.vue, techUpFrontend/pinia/useCartStore.js
장바구니에서 항목 삭제 시 정상 표시 안되는 오류 수정
장바구니 품목 합계 금액 표시 오류 수정
=> 장바구니 기능 오류 수정

techUpFrontend/components/header/component/top-menu.vue
BTS-146, 147 리스트가 비회원에게 노출될 수 있는 오류 수정
=> [fix] 로그아웃 시 위시리스트, 장바구니 정보 초기화

techUpFrontend/components/checkout/checkout-order.vue, techUpFrontend/package-lock.json, techUpFrontend/package.json, techUpFrontend/pinia/useCartStore.js
프론트엔드에서 portone api를 사용해서 결제를 진행하도록 결제 기능 추가
백엔드에서는 검증을 진행한다(검증 기능 미구현)
BTS - 119
=> [feat] 결제 기능 추가

techUpFrontend/components/product-details/product-details-thumb.vue, techUpFrontend/components/product/fashion/product-item.vue, techUpFrontend/components/product/list-item.vue, techUpFrontend/pinia/useProductBackStore.js
기존의 이미지 대신 상품 등록한 사진이 출력되도록 수정 완료.
=> [fix] 제품 목록 및 상세보기에서 사진 안나오는 오류 수정

techUpFrontend/components/order/order-area.vue, techUpFrontend/pages/order/[orderId].vue, techUpFrontend/pinia/useCartStore.js
BTS-160 결제 상세 페이지 제작, 결제 상세 페이지로 이동하도록 수정 완료.
=> 결제 성공 시 결제 상세 내역으로 이동

techUpFrontend/components/admin/admin-alert-item.vue, techUpFrontend/components/admin/admin-alert.vue, techUpFrontend/components/admin/admin-area-userorder.vue, techUpFrontend/components/admin/admin-notifications.vue, techUpFrontend/components/admin/admin-order-item.vue, techUpFrontend/components/admin/admin-user-item.vue, techUpFrontend/components/admin/admin-userorder.vue, techUpFrontend/components/admin/offcanvas-order-details.vue, techUpFrontend/pinia/useAdminStore.js, techUpFrontend/views/dashboard/AnalyticsMonthlyOverview.vue, techUpFrontend/views/dashboard/AnalyticsSalesRanking.vue, techUpFrontend/views/dashboard/AnalyticsTopWishlist.vue
대시보드 통계를 백엔드에서 제대로 받도록 수정하였고
사용자 주문 목록이 제대로 나오게 수정함
=> [Fix] 주문 관련 데이터 수정

techUpFrontend/components/checkout/checkout-area.vue, techUpFrontend/components/checkout/checkout-order.vue, techUpFrontend/components/order/order-area.vue, techUpFrontend/components/profile/profile-orders.vue, techUpFrontend/pinia/useUserOrderStore.js
마이페이지 주문 내역 확인 기능 추가 및 주문 페이지 디테일 수정
=> 마이페이지 주문 내역 확인 기능 추가

techUpFrontend/components/categories/fashion.vue, techUpFrontend/components/order/order-area.vue, techUpFrontend/components/profile/profile-orders.vue, techUpFrontend/pages/order/[orderId].vue
BTS-85 사용자가 환불 요청을 할 수 있도록 주문 확인 페이지에 버튼 추가
=> [feat] 사용자가 환불 요청을 할 수 있도록 주문 확인 페이지에 버튼 추가

techUpFrontend/components/forms/review-form.vue, techUpFrontend/components/product-details/product-details-area.vue, techUpFrontend/components/product-details/product-details-tab-nav.vue, techUpFrontend/pages/product-details/[idx].vue, techUpFrontend/pinia/useReviewStore.js
BTS- 130, 162, 163 상품 리뷰 작성 기능, 리뷰 평점에 맞는 별 출력, 상품별 리뷰 출력 기능 구현
=> [feat] 상품 리뷰 기능 추가

techUpFrontend/components/checkout/checkout-order.vue
해킹 방지 차원에서 백엔드에도 검증 로직 추가 BTS-154
=> [feat] 총 주문 금액이 50000원 미만이라면 무료배송 불가 기능 추가

techUpFrontend/components/checkout/checkout-area.vue, techUpFrontend/components/checkout/checkout-verify.vue, techUpFrontend/pinia/useCartStore.js, techUpFrontend/pinia/useCouponStore.js, techUpFrontend/pinia/useProductFilterBackStore.js
BTS-153 결제 시 쿠폰을 선택한다면 선택한 쿠폰의 상품을 할인한다.
=> 결제 시 쿠폰을 사용한다면 해당 상품 할인 적용

techUpFrontend/components/shop/shop-area.vue, techUpFrontend/components/shop/sidebar/filter-categories.vue, techUpFrontend/pinia/useProductFilterBackStore.js
Reverts beyond-sw-camp/be12-fin-404Found-Tech-Up-FE#122
=> Revert "[Fix] 메인페이지 카테고리 접근"

techUpFrontend/components/admin/offcanvas-order-details.vue, techUpFrontend/components/banner/banner-area-2.vue, techUpFrontend/components/offcanvas/offcanvas-cart-sidebar.vue, techUpFrontend/components/product-details/product-details-wrapper.vue, techUpFrontend/components/product/item.client.vue, techUpFrontend/components/product/product-related.vue, techUpFrontend/components/product/sm-item.vue, techUpFrontend/pages/product-details/[idx].vue, techUpFrontend/pinia/useProductBackStore.js, techUpFrontend/utils/index.js
상품 상세 페이지 관련 상품에서 이미지가 출력되지 않는 오류 수정
원화 표시 소수점 표시 및 , 표시 수정
=> [fix] 디테일 수정

techUpFrontend/components/header/header-one.vue, techUpFrontend/components/shop/shop-area.vue, techUpFrontend/components/shop/sidebar/filter-categories.vue, techUpFrontend/pages/search.vue, techUpFrontend/pinia/useProductFilterBackStore.js
백엔드의 [PR #197](https://github.com/beyond-sw-camp/be12-fin-404Found-Tech-Up-BE/pull/197)에 대응합니다.
=> [Fix] 레거시 제품 목록 및 검색 기능 - 추가 수정

techUpFrontend/pinia/useAdminStore.js, techUpFrontend/pinia/useDeviceStore.js, techUpFrontend/pinia/useMainStore.js, techUpFrontend/pinia/useProductBackStore.js, techUpFrontend/pinia/useProductFilterBackStore.js
=> [Fix] product 백엔드 대응

techUpFrontend/components/shop/sidebar/filter-categories.vue, techUpFrontend/components/shop/sidebar/price-filter.vue, techUpFrontend/k8s/frontend-ssl-conf.yml, techUpFrontend/pages/search.vue, techUpFrontend/pinia/useProductFilterBackStore.js
뷰 라우터 push로 URL에 category 파라미터 강제 주입
=> [Fix] 제품 목록 페이지네이션 오류 수정
